# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(803, 700)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background: #DCDCDC    ;  border: 0px solid black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.training_button = QtWidgets.QPushButton(self.centralwidget)
        self.training_button.setGeometry(QtCore.QRect(0, 0, 411, 61))
        self.training_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/training_mode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.training_button.setIcon(icon)
        self.training_button.setIconSize(QtCore.QSize(400, 55))
        self.training_button.setObjectName("training_button")
        self.testing_button = QtWidgets.QPushButton(self.centralwidget)
        self.testing_button.setGeometry(QtCore.QRect(400, 0, 401, 61))
        self.testing_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/testing_mode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.testing_button.setIcon(icon1)
        self.testing_button.setIconSize(QtCore.QSize(400, 55))
        self.testing_button.setObjectName("testing_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 63, 794, 471))
        self.label.setStyleSheet("background: white; border: 3px solid black")
        self.label.setText("")
        self.label.setObjectName("label")
        self.forward = QtWidgets.QPushButton(self.centralwidget)
        self.forward.setGeometry(QtCore.QRect(270, 538, 111, 111))
        self.forward.setStyleSheet("")
        self.forward.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/before/gui_arrow_up_before.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward.setIcon(icon2)
        self.forward.setIconSize(QtCore.QSize(111, 111))
        self.forward.setObjectName("forward")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(550, 538, 111, 111))
        self.left.setStyleSheet("")
        self.left.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/before/gui_arrow_left_before.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left.setIcon(icon3)
        self.left.setIconSize(QtCore.QSize(111, 111))
        self.left.setObjectName("left")
        self.reverse = QtWidgets.QPushButton(self.centralwidget)
        self.reverse.setGeometry(QtCore.QRect(410, 538, 111, 111))
        self.reverse.setStyleSheet("")
        self.reverse.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/before/gui_arrow_down_before.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reverse.setIcon(icon4)
        self.reverse.setIconSize(QtCore.QSize(111, 111))
        self.reverse.setObjectName("reverse")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(688, 538, 111, 111))
        self.right.setStyleSheet("")
        self.right.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("assets/before/gui_arrow_right_before.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right.setIcon(icon5)
        self.right.setIconSize(QtCore.QSize(111, 111))
        self.right.setObjectName("right")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutonomousRC Companion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
